services:
  social-db:
    build: ./backend/internal/database
    env_file:
      - ./backend/internal/database/.env
    volumes:
      - social-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  social-backend:
    build: ./backend
    container_name: social-backend
    env_file:
      - ./backend/.env
    depends_on:
      social-db:
        condition: service_healthy
  
  social-frontend:
    build: ./front
    depends_on:
      - social-backend

  social-caddy:
    build: ./caddy
    # We only access Caddy so only expose Caddy ports
    ports:
      - "8080:8080"
      - "8081:8080"
    depends_on:
      - social-backend
      - social-frontend

volumes:
  social-db-data:
