package event

const (
	// User events
	SEND_MESSAGE      = "SEND_MESSAGE"
	NOTIFICATION      = "NOTIFICATION"
	TYPING            = "TYPING"
	CHAT_OPENED       = "CHAT_OPENED"
	CHAT_CLOSED       = "CHAT_CLOSED"
	GET_MESSAGES      = "GET_MESSAGES"
	GET_NOTIFICATIONS = "GET_NOTIFICATIONS"
	USERLIST          = "USERLIST"
)
