package event

const (
	SEND_MESSAGE = "SEND_MESSAGE"

	// User events
	// SEND_MESSAGE_TO_USER = "SEND_MESSAGE_TO_USER"

	// // Group events
	// SEND_MESSAGE_TO_GROUP = "SEND_MESSAGE_TO_GROUP"

	// chat events
	TYPING       = "TYPING"
	CHAT_OPENED  = "CHAT_OPENED"
	CHAT_CLOSED  = "CHAT_CLOSED"
	GET_MESSAGES = "GET_MESSAGES"

	// Notification events
	NOTIFICATION_READ = "NOTIFICATION_READ"
	NOTIFICATION      = "NOTIFICATION"
	GET_NOTIFICATIONS = "GET_NOTIFICATIONS"

	// UserList events
	USERLIST = "USERLIST"
)
